### ISSUE TITLE
Impenetrable failure trying to build

### ISSUE THREAD

**Issue by alecmce** [bazelbuild/rules_closure#152]
Can anyone shed any light on how you could work out what is failing from this error? When I add --verbose_failures, I get almost exactly the same error (just the command that is run in parentheses, but the same stack trace and no more useful information). Is there a log somewhere that I can inspect? Thanks in advance.

BUILD:8:1: Checking 46 JS files in //client:library failed: jschecker failed: error executing command bazel-out/local-fastbuild/bin/external/io_bazel_rules_closure/java/com/google/javascript/jscomp/jschecker @bazel-out/local-fastbuild/bin/client/library_worker_input: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at com.google.javascript.jscomp.parsing.IRFactory.normalizeRegex(IRFactory.java:2848)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processRegExpLiteral(IRFactory.java:1725)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processLiteralExpression(IRFactory.java:2628)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2715)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:768)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpressionHelper(IRFactory.java:1393)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processBinaryExpression(IRFactory.java:1376)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2639)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:768)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processExpressionStatement(IRFactory.java:1156)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2669)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:768)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1025)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2713)
        at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:357)
        at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:126)
        at com.google.javascript.jscomp.JsAst.parse(JsAst.java:143)
        at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:53)
        at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:118)
        at com.google.javascript.jscomp.Compiler.hoistExterns(Compiler.java:1575)
        at com.google.javascript.jscomp.Compiler.orderInputs(Compiler.java:1527)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1462)
        at com.google.javascript.jscomp.Compiler.parse(Compiler.java:767)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:723)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:690)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:687)
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:118)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:717)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:687)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:657)
        at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:294)
        at com.google.javascript.jscomp.JsChecker.processRequest(JsChecker.java:356)
        at com.google.javascript.jscomp.JsChecker.main(JsChecker.java:399)
Target //client:binary failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by gramic** [comment]
Sometimes using --sandbox_debug, and then executing the command ([details](https://bazel.io/blog/2016/03/18/sandbox-easier-debug.html)) helps.
Your case looks very similar to #141.

**Comment by jart** [comment]
This is a very interesting error. It appears you've discovered a regular expression that causes the Closure Compiler to crash. The Lord of JavaScript Compilation @MatrixFrog is going to want to know about this.

**Comment by jart** [comment]
Is there any chance you could pinpoint exactly which regex literal is triggering this in your source code? Would any of those sources happen to be open source so we can reproduce this?

**Comment by alecmce** [comment]
It would appear the error comes from an ES6 typo "export = Foo" instead of "exports = Foo".

**Comment by MatrixFrog** [comment]
I can't seem to repro this just from that: https://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('x')%253B%250A%250Avar%2520foo%253B%250A%250Aexport%2520%253D%2520foo%253B%26input1%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26LANG_IN_IS_ES6%3D1%26MISSING_PROPERTIES%3D1%26PRESERVE_TYPE_ANNOTATIONS%3D1%26PRETTY_PRINT%3D1%26TRANSPILE%3D1

The stack trace might be enough to come up with a repro though. I'll try to do that soon.

**Comment by MatrixFrog** [comment]
Interesting that the export vs. exports typo somehow triggers this. Having the regex literal would still be helpful I think.

**Comment by jart** [comment]
Closing because we can't seem to reproduce and inactivity. If new information is provided, I'll reopen this.
