### ISSUE TITLE
0.4.1 --new_type_inf causes "INTERNAL COMPILER ERROR"

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#187]
When using 0.4.1 I am experiencing the following internal compiler error:

```
ahochhaus@ahochhaus-pc:~/rules_closure$ git diff closure/compiler/
diff --git a/closure/compiler/test/BUILD b/closure/compiler/test/BUILD
index dd45b6c..35b640e 100644
--- a/closure/compiler/test/BUILD
+++ b/closure/compiler/test/BUILD
@@ -29,6 +29,7 @@ closure_js_library(
 closure_js_binary(
     name = "hello_bin",
     deps = [":hello_lib"],
+    defs = ["--new_type_inf"],
 )
ahochhaus@ahochhaus-pc:~/rules_closure$ bazel build ...
WARNING: /home/ahochhaus/rules_closure/closure/compiler/closure_js_library.bzl:38:5: The closure_js_library 'language' attribute is now removed and is always set to ECMASCRIPT6_STRICT.
INFO: Found 274 targets...
ERROR: /home/ahochhaus/rules_closure/closure/compiler/test/BUILD:29:1: Compiling 3 JavaScript files to closure/compiler/test/hello_bin.js failed: Worker process sent response with exit code: 1.
ERROR: Worker threw uncaught exception with args: JsCompiler --js_output_file bazel-out/local-fastbuild/bin/closure/compiler/test/hello_bin.js --create_source_map bazel-out/local-fastbuild/bin/closure/compiler/test/hello_bin.js.map --output_errors bazel-out/local-fastbuild/bin/closure/compiler/test/hello_bin-stderr.txt --language_in ECMASCRIPT6_STRICT --language_out ECMASCRIPT5 --compilation_level ADVANCED --dependency_mode LOOSE --warning_level VERBOSE --generate_exports --process_closure_primitives --define=goog.json.USE_NATIVE_JSON --define=goog.soy.REQUIRE_STRICT_AUTOESCAPE --hide_warnings_for=closure/goog/base.js --define=goog.DEBUG=false --info bazel-out/local-fastbuild/bin/closure/compiler/test/hello_lib.pbtxt --js_module_root bazel-out/local-fastbuild/bin/external/io_bazel_rules_closure --js_module_root bazel-out/local-fastbuild/bin --js_module_root external/io_bazel_rules_closure --source_map_location_mapping bazel-out/local-fastbuild/bin/closure/compiler/test/hello_bin.js|hello_bin.js --source_map_include_sources_content --source_map_location_mapping  [synthetic:| [synthetic: --source_map_location_mapping bazel-out/local-fastbuild/bin/external/io_bazel_rules_closure/|/ --source_map_location_mapping bazel-out/local-fastbuild/bin/|/ --source_map_location_mapping external/io_bazel_rules_closure/|/ --source_map_location_mapping |/ --export_test_functions --use_types_for_optimization external/com_google_javascript_closure_library/closure/goog/base.js external/com_google_javascript_closure_library/closure/goog/deps.js closure/compiler/test/hello.js --new_type_inf
java.lang.RuntimeException: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(GETPROP): external/com_google_javascript_closure_library/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;
  Parent(EXPR_RESULT): external/com_google_javascript_closure_library/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;
        at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
        at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:740)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:710)
        at com.google.javascript.jscomp.Compiler.compile(Compiler.java:680)
        at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1080)
        at com.google.javascript.jscomp.JsCompilerRunner.go(JsCompilerRunner.java:44)
        at com.google.javascript.jscomp.JsCompiler.run(JsCompiler.java:189)
        at com.google.javascript.jscomp.JsCompiler.apply(JsCompiler.java:78)
        at io.bazel.rules.closure.ClosureWorker.apply(ClosureWorker.java:56)
        at io.bazel.rules.closure.BazelWorker.runAsPersistentWorker(BazelWorker.java:98)
        at io.bazel.rules.closure.BazelWorker.apply(BazelWorker.java:74)
        at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:93)
Caused by: java.lang.RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

null
  Node(GETPROP): external/com_google_javascript_closure_library/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;
  Parent(EXPR_RESULT): external/com_google_javascript_closure_library/closure/goog/base.js:67:0
goog.global.CLOSURE_UNCOMPILED_DEFINES;

        at com.google.common.base.Preconditions.checkState(Preconditions.java:429)
        at com.google.javascript.jscomp.newtypes.NominalType.getRawNominalType(NominalType.java:59)
        at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getNamedTypeHelper(JSTypeCreatorFromJSDoc.java:427)
        at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromCommentHelper(JSTypeCreatorFromJSDoc.java:297)
        at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeFromComment(JSTypeCreatorFromJSDoc.java:274)
        at com.google.javascript.jscomp.newtypes.JSTypeCreatorFromJSDoc.getTypeOfCommentNode(JSTypeCreatorFromJSDoc.java:239)
        at com.google.javascript.jscomp.GlobalTypeInfo.createTypeFromCommentNode(GlobalTypeInfo.java:2726)
        at com.google.javascript.jscomp.ImplicitNullabilityCheck$2.visit(ImplicitNullabilityCheck.java:121)
        at com.google.javascript.jscomp.NodeUtil.visitPreOrder(NodeUtil.java:3976)
        at com.google.javascript.jscomp.NodeUtil.visitPreOrder(NodeUtil.java:3980)
        at com.google.javascript.jscomp.ImplicitNullabilityCheck.visit(ImplicitNullabilityCheck.java:80)
        at com.google.javascript.jscomp.CombinedCompilerPass$CallbackWrapper.visitOrMaybeActivate(CombinedCompilerPass.java:123)
        at com.google.javascript.jscomp.CombinedCompilerPass.visit(CombinedCompilerPass.java:178)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:643)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
        at com.google.javascript.jscomp.NodeTraversal.traverseChildren(NodeTraversal.java:715)
        at com.google.javascript.jscomp.NodeTraversal.traverseBranch(NodeTraversal.java:639)
        at com.google.javascript.jscomp.NodeTraversal.traverse(NodeTraversal.java:316)
        at com.google.javascript.jscomp.NodeTraversal.traverseEs6(NodeTraversal.java:586)
        at com.google.javascript.jscomp.CombinedCompilerPass.process(CombinedCompilerPass.java:154)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:296)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:228)
        at com.google.javascript.jscomp.Compiler.check(Compiler.java:873)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:766)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:713)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:710)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:91)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
        ... 35 more
INFO: Elapsed time: 0.761s, Critical Path: 0.62s
```

I have yet to test if this is a compiler or rules_closure regression.

**Comment by MatrixFrog** [comment]
@dimvar

**Comment by hochhaus** [comment]
I did more testing to determine this is actually a bug with the upstream compiler (https://github.com/google/closure-compiler/issues/2333).
