### ISSUE TITLE
normalizeRegex StringIndexOutOfBounds

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#188]
I accidentally pasted some spurious content at the frontmatter of a file and caused this exception:

```javascript
goog.provide('v1.jats.io.Writer');

  /writer.js:3: ERROR lintChecks JSC_REQUIRES_NOT_SORTED - goog.require() statements are not sorted. The correct order is:

goog.require('goog.Promise');
...
```

```java
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:126)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:740)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:710)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:680)
	at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:270)
	at com.google.javascript.jscomp.JsChecker.access$200(JsChecker.java:57)
	at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:331)
	at io.bazel.rules.closure.ClosureUberAlles.apply(ClosureUberAlles.java:41)
	at io.bazel.rules.closure.BazelWorker.runAsPersistentWorker(BazelWorker.java:84)
	at io.bazel.rules.closure.BazelWorker.apply(BazelWorker.java:60)
	at io.bazel.rules.closure.ClosureUberAlles.main(ClosureUberAlles.java:31)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.google.javascript.jscomp.parsing.IRFactory.normalizeRegex(IRFactory.java:2850)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processRegExpLiteral(IRFactory.java:1727)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processLiteralExpression(IRFactory.java:2630)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2717)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processExpressionStatement(IRFactory.java:1160)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2671)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1029)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2715)
	at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:353)
	at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:131)
	at com.google.javascript.jscomp.JsAst.parse(JsAst.java:142)
	at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:52)
	at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:118)
	at com.google.javascript.jscomp.Compiler.hoistIfExtern(Compiler.java:1675)
	at com.google.javascript.jscomp.Compiler.hoistUnorderedExterns(Compiler.java:1645)
	at com.google.javascript.jscomp.Compiler.orderInputs(Compiler.java:1596)
	at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1531)
	at com.google.javascript.jscomp.Compiler.parse(Compiler.java:791)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:747)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:84)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:713)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:710)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:116)
	... 10 more
```

Not a big deal, but I thought I'd post it here in case others come across it.

```python
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    tag = "0.4.1",
)
```

**Comment by MatrixFrog** [comment]
This is a bug in the compiler itself. Follow https://github.com/google/closure-compiler/issues/2340
