### ISSUE TITLE
plugin_modules doesn't work

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_closure#197]
closure_js_template_library says plugin_modules should be a label, but it passes this directly to the compiler. The compiler wants the name of a class (which also needs to be on the classpath).
I tried using a java_library, which has two classes -- my custom directive and a guice module to load it. But that fails like this:
ERROR: Generating 1 SOY v2 JS file(s) failed: Process exited with status 1 [sandboxed].
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.lang.RuntimeException: Cannot instantiate plugin module "ConfiguredTarget(//soy/plugins:directives".
	at com.google.template.soy.MainClassUtils.instantiatePluginModule(MainClassUtils.java:364)
	at com.google.template.soy.MainClassUtils.access$000(MainClassUtils.java:49)
	at com.google.template.soy.MainClassUtils$ModuleListOptionHandler.parseItem(MainClassUtils.java:174)
	at com.google.template.soy.MainClassUtils$ModuleListOptionHandler.parseItem(MainClassUtils.java:164)
	at com.google.template.soy.MainClassUtils$ListOptionHandler.parseArguments(MainClassUtils.java:136)
	at com.google.template.soy.MainClassUtils$ModuleListOptionHandler.parseArguments(MainClassUtils.java:164)
	at org.kohsuke.args4j.CmdLineParser.parseArgument(CmdLineParser.java:508)
	at com.google.template.soy.MainClassUtils.parseFlags(MainClassUtils.java:236)
	at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:164)
	at com.google.template.soy.AbstractSoyCompiler.access$000(AbstractSoyCompiler.java:43)
	at com.google.template.soy.AbstractSoyCompiler$2.main(AbstractSoyCompiler.java:158)
	at com.google.template.soy.MainClassUtils.runInternal(MainClassUtils.java:253)
	at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:154)
	at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:146)
	at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:192)
Caused by: java.lang.ClassNotFoundException: ConfiguredTarget(//soy/plugins:directives
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.google.template.soy.MainClassUtils.instantiatePluginModule(MainClassUtils.java:361)
	... 14 more

**Comment by robfig** [comment]
I need this feature.. @Yannic, do you have any guidance on what the implementation should look like? 

In particular, I'm not sure how best to modify the classpath that SoyToJsSrcCompiler gets run with. It looks like the generated wrapper script does not support extra values in the CLASSPATH env var, and I'm seeing an error when (ab)using --main_advice_classpath, although it might be a red herring.

Here's the code I'm looking at:
https://github.com/robfig/rules_closure/commit/3344eb737729584ddb7aef309f49adedaa982a96

Here's the error I'm seeing:
```
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file com/google/template/soy/SoyToJsSrcCompiler
```

**Comment by Yannic** [comment]
TIL about `—main_advice_classpath` :).

First, you might want to take a look at `JavaInfo#transitive_runtime_jars`. `compile_jars` contains targets that are marked as `neverlink = True`.

For adding the plugin to the classpath, I suggest the following approach:
```python
transitive_inputs = []
for dep in ctx.attr.plugin_module_deps:
  transitive_inputs.append(dep[JavaInfo].transitive_runtime_jars)
args = ["--main_advice_classpath=" + ":".join([jar.path for jar in depset([], transitive=transitive_inputs).to_list()])]

# ...

inputs = []

# ...

ctx.actions.run(
  inputs = depset(inputs, transitive=transitive_inputs),
)
```

If that still shows the same error, try also adding `ctx.attr.compiler[JavaInfo].transitive_runtime_jars` to `transitive_inputs`.

Also, there‘s no need to return `runfiles`, we‘re running an action here and don‘t produce an executable.

**Comment by robfig** [comment]
Thank you! Got it working, added a test, submitted a PR

**Comment by robfig** [comment]
As an aside, I get other errors which I'm able to suppress, but which I don't understand. Just curious if you happen to know what they are about. 

When building the closure_js_template_library rule, it generates JS source without a problem, but then the type checking of that rule fails:
```
bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/ClosureWorker JsCompiler
 --checks_only
 --warning_level VERBOSE
 --jscomp_off reportUnknownTypes
 --language_in ECMASCRIPT_2017
 --language_out ECMASCRIPT5
 --js_output_file bazel-out/darwin-fastbuild/bin/src/com/corp/fieldsstorm/app/views/CustomFieldsStorm/entityTypes_soyjs_typecheck
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/debug/error.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/nodetype.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/asserts/asserts.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/array/array.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/debug/errorcontext.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/string/internal.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/labs/useragent/util.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/object/object.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/labs/useragent/browser.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/string/string.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/labs/useragent/engine.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/labs/useragent/platform.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/reflect/reflect.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/useragent/useragent.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/debug/debug.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/uchar.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/structs/inversionmap.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/graphemebreak.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/format/format.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/htmlelement.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/tagname.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/tags.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/trustedtypes.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/string/typedstring.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/string/const.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/safescript.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/fs/url.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/bidi.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/trustedresourceurl.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/safeurl.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/safestyle.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/safestylesheet.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/safehtml.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/html/uncheckedconversions.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/bidiformatter.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/compactnumberformatsymbols.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/currency.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/numberformatsymbols.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/math/math.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/i18n/numberformat.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/soy/all_js.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/structs/structs.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/functions/functions.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/iter/iter.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/structs/map.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/uri/utils.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/uri/uri.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/soy/data.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/browserfeature.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/asserts.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/safe.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/math/coordinate.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/math/size.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/dom/dom.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/soy/soy.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/soy/renderer.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/crypt/crypt.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library/useragent/product.i.js'
 '--externs=bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/library//** @fileoverview @typeSummary */
```

I see errors like this:
```
bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/protobuf/jspb.i.js:207: ERROR - required "jspb.utils" namespace not provided yet
goog.require("jspb.utils");
^
  Codes: JSC_LATE_PROVIDE_ERROR, lateProvide

bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/protobuf/jspb.i.js:511: ERROR - required "jspb.utils" namespace not provided yet
goog.require("jspb.utils");
^
  Codes: JSC_LATE_PROVIDE_ERROR, lateProvide

bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/protobuf/jspb.i.js:1899: ERROR - required "jspb.Map" namespace not provided yet
goog.require("jspb.Map");
^
  Codes: JSC_LATE_PROVIDE_ERROR, lateProvide

bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/protobuf/jspb.i.js:1900: ERROR - required "jspb.Message" namespace not provided yet
goog.require("jspb.Message");
^
  Codes: JSC_LATE_PROVIDE_ERROR, lateProvide

bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_closure/closure/templates/soy_jssrc.i.js:190: ERROR - required "soydata.VERY_UNSAFE" namespace not provided yet
goog.require("soydata.VERY_UNSAFE");
^
  Codes: JSC_LATE_PROVIDE_ERROR, lateProvide

5 error(s), 0 warning(s)
```

Suppressing lateProvide gets me past that; e.g. the jspb.utils provide is in the same file, farther down. But it seems like it indicates another problem with the rule (or maybe just a mismatch with the version of Closure Library I'm using?).

**Comment by Yannic** [comment]
I‘ve never seen this error, sorry.

It seems like this could be an ordering issue with the files which should be safe to suppress, but that‘s just a wild guess.
If you can provide a repro repo, I might be able to take a look (but it could be a while until I get to that).
