### ISSUE TITLE
Closure is broken at HEAD since http://ci.bazel.io/job/rules_closure/814/

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_closure#203]
http://ci.bazel.io/job/rules_closure/814/ List the commits that can be culprit:

Don't String#intern() web paths (commit: db6033c) (detail / githubweb)
Add suppression support to library-level checking rule (commit: 2159f3f) (detail / githubweb)
Upgrade Closure Compiler and Closure Library (commit: 47a076d) (detail / githubweb)

**Comment by MatrixFrog** [comment]
Interesting. Something going wrong in the CodeGenerator but it's not clear exactly what. http://ci.bazel.io/job/rules_closure/814/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console

**Comment by kaspnilsson** [comment]
@MatrixFrog FWIW https://github.com/bazelbuild/rules_closure/issues/202 also references this same error. 

I'm able to semi-consistently reproduce it with our build... Maybe 2/3 of builds fail.

**Comment by jart** [comment]
I'm unable to reproduce this error locally for some reason. Still investigating.

```
____[722 / 864] Checking 815 JS files in //closure/library:library
ERROR: /home/ci/workspace/rules_closure/BAZEL_VERSION/latest/PLATFORM_NAME/linux-x86_64/closure/library/BUILD:22:1: Checking 815 JS files in //closure/library:library failed: Worker process did not return a WorkResponse. This is probably caused by a bug in the worker, writing unexpected other data to stdout..
WARNING: Closure worker (id 5) can no longer be used, because its process terminated itself or got killed.
```

Those errors are the bane of my existence, since Bazel doesn't print what happened. It's possible that it's some type of error when loading classes.

**Comment by jart** [comment]
It seems like the failure on Mac actually did give us more information.

```
____[270 / 296] Checking 1 JS files in //closure/compiler/test:extern_lib
ERROR: /Users/ci/workspace/rules_closure/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/closure/library/BUILD:22:1: Checking 815 JS files in //closure/library:library failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log snippet, file at /private/var/tmp/_bazel_ci/b57475fbb54d8e3c6745c9da4dd72521/bazel-workers/worker-6-Closure.log ---8<---8<---
[... truncated ...]
IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
	at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:767)
	at com.google.javascript.jscomp.parsing.IRFactory.transformBlock(IRFactory.java:614)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processIfStatement(IRFactory.java:1360)
	at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2689)
---8<---8<--- End of log snippet, 92864 chars omitted ---8<---8<---.
____Elapsed time: 25.788s, Critical Path: 9.88s
Build step 'Conditional steps (multiple)' marked build as failure
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: Test reports were found but none of them are new. Did tests run? 
For example, /Users/ci/workspace/rules_closure/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/bazel-testlogs/closure/compiler/test/closure_js_deps/dataAttributeReferencingJsDeps_providesDepsFileSourcesAndData/test.xml is 25 days old
```

@MatrixFrog do you know what this might be? I just upgraded Closure Compiler. I'm using the unshaded jar.

**Comment by jart** [comment]
I think I see what the problem might be.

**Comment by damienmg** [comment]
Any news on that issue?

**Comment by jart** [comment]
This is a hard problem to fix, since the logs aren't informative, it's flaky on Jenkins and Travis, and I can't reproduce it at all on my workstation.

I've got one last hail mary I can throw at this problem. I'm going to increase the Java stack size. Expect a CL shortly.

**Comment by damienmg** [comment]
That worked, nice! Thank you!

**Comment by jart** [comment]
![Yes!](http://i.imgur.com/6PTeQuW.png)
