### ISSUE TITLE
NullPointerException in JSChecker

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/rules_closure#227]
Might be a bug in closure compiler (@MatrixFrog), but since I wasn't able to find any repo case for the compiler I'm reporting it here.
The crash only happens when there is a syntax error in the code.

```javascript
class Foo {
  /** @return {number} */
  status() { return 0; } 

  /** @return {!Object<string, *>} */
  toCFResponse() {
    const headers = {
      'server': [{'key': 'Server', 'value': 'MyCustomOrigin'}],
      'set-cookie': [
        {'key': 'Set-Cookie', 'value': 'theme=light'},
        {
          'key': 'Set-Cookie',
          'value': 'sessionToken=abc123; Expires=Wed, 09 Jun 2021 10:18:14 GMT'
        },
      ]
    };

    return {
      'status': this.status().toString(),
      'statusDescription': 'OK',
      'headers': headers;  // The syntax error is here!
    };
  }
}
```

```
java.lang.NullPointerException
	at com.google.javascript.jscomp.ConvertToTypedInterface$SimplifyDeclarations.processFunction(ConvertToTypedInterface.java:523)
	at com.google.javascript.jscomp.ConvertToTypedInterface$SimplifyDeclarations.processClass(ConvertToTypedInterface.java:518)
	at com.google.javascript.jscomp.ConvertToTypedInterface$SimplifyDeclarations.processName(ConvertToTypedInterface.java:502)
	at com.google.javascript.jscomp.ConvertToTypedInterface$SimplifyDeclarations.simplifyAll(ConvertToTypedInterface.java:482)
	at com.google.javascript.jscomp.ConvertToTypedInterface.processFile(ConvertToTypedInterface.java:93)
	at com.google.javascript.jscomp.ConvertToTypedInterface.process(ConvertToTypedInterface.java:84)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:304)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:230)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:1072)
	at com.google.javascript.jscomp.Compiler.performChecksAndTranspilation(Compiler.java:874)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:102)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:808)
	at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:805)
	at com.google.javascript.jscomp.CompilerExecutor.runInCompilerThread(CompilerExecutor.java:128)
	at com.google.javascript.jscomp.Compiler.runInCompilerThread(Compiler.java:862)
	at com.google.javascript.jscomp.Compiler.stage1Passes(Compiler.java:804)
	at com.google.javascript.jscomp.Compiler.compile(Compiler.java:721)
	at com.google.javascript.jscomp.JsChecker.run(JsChecker.java:249)
	at com.google.javascript.jscomp.JsChecker.access$300(JsChecker.java:63)
	at com.google.javascript.jscomp.JsChecker$Program.apply(JsChecker.java:341)
	at io.bazel.rules.closure.worker.LegacyAspect.run(LegacyAspect.java:38)
	at io.bazel.rules.closure.ClosureWorker.run(ClosureWorker.java:69)
	at io.bazel.rules.closure.worker.PersistentWorker.runProgram(PersistentWorker.java:109)
	at io.bazel.rules.closure.worker.PersistentWorker.runAsPersistentWorker(PersistentWorker.java:144)
	at io.bazel.rules.closure.worker.PersistentWorker.run(PersistentWorker.java:84)
	at io.bazel.rules.closure.ClosureWorker.main(ClosureWorker.java:111)
```

**Comment by MatrixFrog** [comment]
@lauraharker can you take a look?

**Comment by lauraharker** [comment]
Sure, I’ll take a look.

**Comment by lauraharker** [comment]
Looks like this was a compiler bug that got fixed in https://github.com/google/closure-compiler/commit/1f25245d1524f24c56d11aa3c5a4205ebec07b4d. The fix is in the latest compiler release v20171023, which Closure Rules hasn't migrated to yet.

**Comment by Yannic** [comment]
Thanks, updating to the latest release fixed it
