### ISSUE TITLE
should_generate_soy_msg_defs requires BiDi directionality

### ISSUE THREAD

**Issue by adam-rocska** [bazelbuild/rules_closure#285]
Given the following `closure_js_template_library` rule : 

```
closure_js_template_library(
    name = "feedback_template",
    srcs = glob(
		[
			"**/*.soy"
		]
	),
    data = [],
    deps = [
        "//demo/epr/src/model"
    ],
    plugin_modules = [],
    should_provide_require_soy_namespaces = True,
    should_generate_soy_msg_defs = True,
    soy_msgs_are_external = False,
)
```

when I execute my build, I get the following exception : 

```
INTERNAL SOY ERROR.
Please open an issue at https://github.com/google/closure-templates/issues with this stack trace and repro steps
java.lang.IllegalStateException: If enabling shouldGenerateGoogMsgDefs, must also set bidi global directionality.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
	at com.google.template.soy.jssrc.internal.JsSrcMain.genJsSrc(JsSrcMain.java:107)
	at com.google.template.soy.jssrc.internal.JsSrcMain.genJsFiles(JsSrcMain.java:151)
	at com.google.template.soy.SoyFileSet.compileToJsSrcFiles(SoyFileSet.java:1021)
	at com.google.template.soy.SoyToJsSrcCompiler.compile(SoyToJsSrcCompiler.java:223)
	at com.google.template.soy.AbstractSoyCompiler.compile(AbstractSoyCompiler.java:315)
	at com.google.template.soy.AbstractSoyCompiler.doMain(AbstractSoyCompiler.java:258)
	at com.google.template.soy.AbstractSoyCompiler.run(AbstractSoyCompiler.java:183)
	at com.google.template.soy.AbstractSoyCompiler.runMain(AbstractSoyCompiler.java:175)
	at com.google.template.soy.SoyToJsSrcCompiler.main(SoyToJsSrcCompiler.java:184)
Target //demo/epr/src/feedback:feedback failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.028s, Critical Path: 1.28s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

Proposed resolution would be to have the ability to provide the global bidi value expected by the soy compiler.

**Comment by robfig** [comment]
I had the same issue and opened PR #350 
cc @gkdn , who seems like the most active reviewer
