### ISSUE TITLE
Incompatibility with bazel 0.23.0

### ISSUE THREAD

**Issue by jianglai** [bazelbuild/rules_closure#333]
The title says it all. With bazel 0.23.0 I got the following output:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /usr/local/google/home/jianglai/.cache/bazel/_bazel_jianglai/c52ec6282bd27be0bdbeba205586bf1a/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl:82:17: Traceback (most recent call last):
        File "/usr/local/google/home/jianglai/.cache/bazel/_bazel_jianglai/c52ec6282bd27be0bdbeba205586bf1a/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 78
                rule(implementation = _impl, attrs = {"...")}, ..."})
        File "/usr/local/google/home/jianglai/.cache/bazel/_bazel_jianglai/c52ec6282bd27be0bdbeba205586bf1a/external/io_bazel_rules_closure/closure/compiler/closure_js_deps.bzl", line 82, in rule
                attr.label_list(cfg = "data", allow_files = True)
Using cfg = "data" on an attribute is a noop and no longer supported. Please remove it. You can use --incompatible_disallow_data_transition=false to temporarily disable this check.
ERROR: error loading package '': in /usr/local/google/home/jianglai/.cache/bazel/_bazel_jianglai/c52ec6282bd27be0bdbeba205586bf1a/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
ERROR: error loading package '': in /usr/local/google/home/jianglai/.cache/bazel/_bazel_jianglai/c52ec6282bd27be0bdbeba205586bf1a/external/io_bazel_rules_closure/closure/defs.bzl: Extension file 'closure/compiler/closure_js_deps.bzl' has errors
INFO: Elapsed time: 10.116s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

I'm using rules_closure 0.8.0. I think the latest version in master already fixed it (it does not have `cfg = "data"` in `closure_js_deps.bzl`, which is what bazel complained about. Maybe this can be fixed simply by cutting a new release?

**Comment by jianglai** [comment]
@guyben13

**Comment by laurentlb** [comment]
Correct. Everything should work at head (we have lots of tests for that - any failure would block a Bazel release). The latest release is a bit old (August) and we've made lots of fixes since that.

I can recommend you to use the latest commit (https://github.com/bazelbuild/rules_closure/commit/87d24b1df8b62405de8dd059cb604fd9d4b1e395) in your repository, this should unblock you. But we should also have a new release in the next few days.
