### ISSUE TITLE
Fix incompatible_depset_union

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_closure#345]
As of Bazel 0.24, `rules_closure` does not build with: `--incompatible_depset_union` option:

```
ERROR: /home/davido/projects/davido_rules_closure/closure/webfiles/test/BUILD:29:1: in web_library rule //closure/webfiles/test:stuff: 
Traceback (most recent call last):
	File "/home/davido/projects/davido_rules_closure/closure/webfiles/test/BUILD", line 29
		web_library(name = 'stuff')
	File "/home/davido/projects/davido_rules_closure/closure/webfiles/web_library.bzl", line 88, in _web_library
		manifests += [manifest]
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//closure/webfiles/test:stuff' failed; build aborted: Analysis of target '//closure/webfiles/test:stuff' failed; build aborted
INFO: Elapsed time: 11.700s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (211 packages loaded, 2431 targets configured)
FAILED: Build did NOT complete successfully (211 packages loaded, 2431 targets configured)
```

**Comment by davido** [comment]
@meteorcloudy, @laurentlb Was this fixed by https://github.com/bazelbuild/rules_closure/pull/352?

**Comment by meteorcloudy** [comment]
I believe not, #352 only fixes `closure/filegroup_external.bzl`
